### ISSUE TITLE
Update Python and ROOT

### ISSUE THREAD

**Issue by fdiblen** [NLeSC/root-conda-recipes#17]

**Comment by fdiblen** [comment]
Latest versions of:
  - [ ] Python 2  and ROOT 5
  - [ ] Python 3 and ROOT 5
  - [ ] Python 2  and ROOT 6
  - [ ] Python 3 and ROOT 6

**Comment by egpbos** [comment]
After discussion, decided to support the following builds:

ROOT: just 6.

Python:
- [ ] 2.7 latest
- [ ] 3 latest

OS:
- [ ] Linux (Ubuntu and Scientific Linux, which are both supported automatically by using Conda)
- [ ] OSX latest

**Comment by fdiblen** [comment]
updated in 3be0a50a8b8b34d1094903b7ab85843bd4f7a086
