### ISSUE TITLE
Python 3.6 builds?

### ISSUE THREAD

**Issue by ndawe** [NLeSC/root-conda-recipes#28]
In the CI for rootpy I'd like to run tests against python 3.6 where there have been some bytecode changes. Could you provide ROOT builds for 3.6?

**Comment by fdiblen** [comment]
Hi, 
It is in our list. We will notify you when we realese it.

**Comment by ndawe** [comment]
Many thanks!

**Comment by ndawe** [comment]
Also a ROOT later than 6.04 to avoid this bug:

https://sft.its.cern.ch/jira/browse/ROOT-7365

Thanks again!

**Comment by remenska** [comment]
@ndawe is the ROOT version important for you? Right now we build ROOT 5 and 6, but I don't think  a version later than 6.04 is in the Anaconda Cloud.

**Comment by ndawe** [comment]
Ah, I see. It's not critical now I suppose. No worries. I'm working on a way to patch in a ``__hash__`` in rootpy instead.

**Comment by remenska** [comment]
I will give it a try with a more recent ROOT and let you know. In the worst case I can do some black magic to cherry pick the patch for that on top of 6.04 :)

**Comment by remenska** [comment]
@ndawe Can you test and see if it works?

```
root@ea870013360b:/$ conda create -n testme root=6.05 python=3.6
...
Activate: ROOT has been sourced. Environment settings are ready.
ROOTSYS=/conda/envs/testme
(testme) root@ea870013360b:/$ root -b -q
   ------------------------------------------------------------
  | Welcome to ROOT 6.05/02                http://root.cern.ch |
  |                               (c) 1995-2014, The ROOT Team |
  | Built for linuxx8664gcc                                    |
  | From tag v6-05-02, 14 September 2015                       |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q' |
   ------------------------------------------------------------

root [0]
(testme) root@ea870013360b:/$ python
Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>> ROOT.gROOT.GetVersion()
>>>'6.05/02'

```

I assume this is the fix for the hash:
https://github.com/root-project/root/commit/3f3f1b1838183f1d6e22ee75515f5c4f5ab8dc79

**Comment by remenska** [comment]
Hmm, rootpy fails the most basic stl tests:

https://travis-ci.org/NLeSC/root-conda-recipes/jobs/232169317

**Comment by remenska** [comment]
Fixed it in the meantime by applying some patches from the official ROOT repository. Enjoy the new binaries!

**Comment by ndawe** [comment]
Thanks a lot! I'll move our 3.4 tests up to 3.6. That must be a ROOT bug that was later fixed. 6.09/1 is ok but then 6.09/2 has another issue....

**Comment by ndawe** [comment]
Unfortunately there is a bus error with ROOT 6.05 in the histogram components. I'd suggest building 6.08 or 6.06 instead.

**Comment by remenska** [comment]
@ndawe Do you happen to know which patch would solve the problem? I cannot compile 6.06 or 6.08, at least not without breaking backwards compatibility with glibc 2.12 (and If I did anyways, I think it would not work with your Ubuntu 12.04 CI boxes on rootpy Travis)

**Comment by Kecksdose** [comment]
@remenska Thanks for updating the conda build of ROOT to work with Python 3.6. Could you please also update `root_numpy` as this is one major package many data analysts may need?

Ah, you already did that! The only thing I had to do is to change the name of the package to `root-numpy`.

**Comment by remenska** [comment]
@Kecksdose Yep it's there
Sorry the old `root_numpy` binaries still linger in anaconda just in case ... Maybe I should remove it :)
