### ISSUE TITLE
Difference between root_numpy and root-numpy? Do I need both?

### ISSUE THREAD

**Issue by morgangillis** [NLeSC/root-conda-recipes#36]
Both packages are listed on the [NLeSC Anaconda repository](https://anaconda.org/NLeSC/repo). I notice that `root-numpy` was last updated much more recently than `root_numpy`.

**Comment by jonas-eschle** [comment]
I think root_numpy is just the "old" name and is only available for python 2 and 3.4 while root-numpy is also available for 3.5 and 3.6.

I would say, you only need root-numpy.
