### ISSUE TITLE
PyROOT first install quirk

### ISSUE THREAD

**Issue by kreczko** [NLeSC/root-conda-recipes#6]
@raggleton and I stumbled across an oddity when installing ROOT via conda: 
The `thisroot.sh` script is only run on `source activate <env>` and PyROOT will not be available right after the installation of ROOT.

To replicate:

``` bash
conda create -n test-root python=2.7
source activate test-root
conda install -c https://conda.anaconda.org/nlesc root
# this will fail
python -c 'import ROOT'
```

Current workaround

``` bash
# following the above
source deactivate
source activate test-root
# one will see "Activate: ROOT has been sourced. Environment settings are ready. "
# now it works
python -c 'import ROOT'
```

The solution would be to source the ROOT environment after a successful install.

**Comment by remenska** [comment]
Unfortunately there seems to be no way to set environment variables other than with activate/deactivate. I thought the pre/post-link scripts would achieve this, but they are run in a subshell, so all variables are lost once the scripts finish.
